### ISSUE TITLE
Mac: when multiple AS instances is opened, OkHttp profile is active only in one window

### ISSUE THREAD

**Issue by xzhorikx** [itkacher/OkHttpProfiler#10]
MacOS version: `10.14.3 Beta (18D32a)`

When multiple instances of Android Studio is opened at the same time, OkHttp Profile is active in only one window (which seems to be chosen randomly). Please see attached screenshots
![image](https://user-images.githubusercontent.com/37912817/56288031-72094980-6150-11e9-9070-3799657c8b09.png)

To the left: AS window that is not currently active - no builds are running. Meanwhile, right window has active build running and I have to navigate between multiple AS windows to find which has OkHttp displayed

**Comment by Nielssg** [comment]
Can confirm that this happens on Windows as well!
Windows version: ```Windows 10 version 1909 (Build 18363.476)```

**Comment by AlienAsRoger** [comment]
Hello! Is there any updates planned on this?

**Comment by gektor650** [comment]
Hi all!
I fixed the issue and submitted the plugin 1.0.10
Will be available in two days.
Sorry for a delay :)

**Comment by gektor650** [comment]
Done. Use 1.0.11
