### ISSUE TITLE
ERROR: Failed to resolve: com.itkacher.okhttpprofiler:okhttpprofiler:1.0.5

### ISSUE THREAD

**Issue by TalbotGooday** [itkacher/OkHttpProfiler#11]
I've got the error: **ERROR: Failed to resolve: com.itkacher.okhttpprofiler:okhttpprofiler:1.0.5** when updated Gradle 
       ` classpath 'com.android.tools.build:gradle:3.5.2' `
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip`

**Comment by nv95** [comment]
Same problem

@TalbotGooday just download jar

**Comment by itkacher** [comment]
Hi @nv95, @TalbotGooday !
Unfortunately,  gradle gradle-6.0.1 is not supported by com.android.tools.build:gradle:3.5.2 
You can check it here:
[https://developer.android.com/studio/releases/gradle-plugin](https://developer.android.com/studio/releases/gradle-plugin)
Please, use:
`distributionUrl = https\://services.gradle.org/distributions/gradle-5.4.1-all.zip` 
and everything will be ok.

**Comment by david1824** [comment]
Hi. After 6 month we have this gradle version by default in new android project. Still have to downgrade?
Thanks

**Comment by david1824** [comment]
Sorry, didnt notice that there is solution on #13
Also 1.0.7 is not mentioned in github releases, though 1.0.5 is the last version.

**Comment by david1824** [comment]
Duplicate of #13
