### ISSUE TITLE
Plugin source code can be open source?

### ISSUE THREAD

**Issue by liangjingkanji** [itkacher/OkHttpProfiler#18]
I want to develop based on you project

**Comment by gektor650** [comment]
Sorry, didn't want to open the code before the migration to gradle. Now it opened and described here:
[https://proandroiddev.com/how-to-create-an-android-studio-plugin-with-the-adb-connection-and-reading-messages-from-the-logcat-1a021a752446](https://proandroiddev.com/how-to-create-an-android-studio-plugin-with-the-adb-connection-and-reading-messages-from-the-logcat-1a021a752446)
Source code:
[https://github.com/gektor650/OkHttpProfiler-AndroidStudio-Plugin](https://github.com/gektor650/OkHttpProfiler-AndroidStudio-Plugin)
