### ISSUE TITLE
Out of memory exeption and crash

### ISSUE THREAD

**Issue by ZaydelEduard** [itkacher/OkHttpProfiler#2]
Crash with large json 
![image](https://user-images.githubusercontent.com/9789176/47356721-86064e00-d6cd-11e8-83aa-28d2245006a4.png)

**Comment by itkacher** [comment]
Fixed in 1.0.1
implementation 'com.itkacher.okhttpprofiler:okhttpprofiler:1.0.1' 
Thanks a lot!)
