### ISSUE TITLE
Bintray is shutting off on May 1st 2021

### ISSUE THREAD

**Issue by iliaskomp** [itkacher/OkHttpProfiler#21]
It seems that OkHttpProfiler is currently hosted on bintray. However, this will be shut down from 1st of May: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Are there any plans to migrate to another repository?

**Comment by rvp-diconium** [comment]
hey @itkacher , sorry to directly "at" you, but considering 1st of May is in 8 days.
Will this be migrated?

**Comment by itkacher** [comment]
Hi!
Sorry for the late reply
Yeap, will migrate it soon
Thanks for the reminder

**Comment by gektor650** [comment]
Thanks for your notifications, the plugin was migrated to Maven Central (but with a different package name).
You should change the old implementation to the:
`implementation 'com.localebro:okhttpprofiler:1.0.8'`
and change package **com.itkacher** to the **com.localebro** in the code.
And everything will work fine.

P.S. old package will be available for at least until:
**February 1st, 2022 | JCenter will no longer be available for non-Artifactory clients.**
So no rush to change something now.

Feel free to ask questions.
Thanks for using the plugin)
