### ISSUE TITLE
Invailid at Android Studio Bumblebee | 2021.1.1 Canary 11

### ISSUE THREAD

**Issue by liangjingkanji** [itkacher/OkHttpProfiler#23]
Plugin does not display logs

Arctic Fox 2020.3.1 Patch 2 availability

**Comment by kleiren** [comment]
With the release of 2021.1.1 it does not seem to work. The plugin does not display logs.

**Comment by gektor650** [comment]
Fixed.
It is waiting for JetBrain's review.
You can manually install it by URL:
https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/155508

**Comment by gektor650** [comment]
Feel free to ping if something wrong.
