### ISSUE TITLE
OkHttpProfiler Plugin not working andriod studio Android Studio Bumblebee | 2021.1.1 for Windows 64-bit

### ISSUE THREAD

**Issue by kazimdsaidul** [itkacher/OkHttpProfiler#26]
Android Studio Bumblebee | 2021.1.1 for Windows 64-bit not working. it works well after the android studio version.

**Comment by gektor650** [comment]
Hi! 
@kazimdsaidul  did you try the latest build?
https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/155508
What version of the plugin do you use?

**Comment by gektor650** [comment]
https://github.com/itkacher/OkHttpProfiler/issues/23
