### ISSUE TITLE
Android Studio Chipmunk | 2021.2.1 Plugin not  display logs.

### ISSUE THREAD

**Issue by indiascope** [itkacher/OkHttpProfiler#30]
Thank You for Great Plugin. After updating to the Latest **Android Studio Chipmunk | 2021.2.1**  OkHttp Profiler Plugin is not displaying any Log.

In All Previous Android Studio Version, OkHttp Profiler Plugin is working fine.

OkHttp Profiler Plugin Version : **1.0.17**. 

I have tried to install Plugin Version **1.0.21** from [plugins.jetbrains.com/](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions) But when I manually tried to install the Plugin I am getting the below error in Android Studio.

![Screenshot from 2022-05-10 13-13-39](https://user-images.githubusercontent.com/3463588/167576085-3b03b553-f472-47a5-98e8-5196485c432e.png)

**Comment by zhaohailongzhl** [comment]
I upgraded androidStudio version to 2021.2.1 and this plugin didn't work

**Comment by zhaohailongzhl** [comment]
Is this problem solved?

**Comment by gektor650** [comment]
Hi, Guys!
Thanks for reporting the issue.
I have uploaded a new version of the plugin (1.0.22). 
It will be available in the market after review, but you can download and install it manually from here:
[1.0.22-stable](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/176490)
You can thank me for my efforts in providing a free tool for developers with a donation to the Ukrainian forces. 
Links are in the plugin.
It can happen that no new version will be available, so it's better to donate :)
