### ISSUE TITLE
Doesn't work with latest Android Studio

### ISSUE THREAD

**Issue by realityexpander** [itkacher/OkHttpProfiler#32]
Just downloaded and test with Android Studio Electric Eel | 2022.1.1 Beta 2

Complaining about missing `local.properties` file. Easy fix, just copied from the plug-in project.

But running the sample app with an emulator and hardware device does nothing, even when selecting the sample app with the pop-ups. Pop-ups also seem to not work properly.

Is work still being done on this project?

How is it better than the App Inspection Network panel?

**Comment by realityexpander** [comment]
Thanks for the quick reply.

The AS versions are changing very fast these days, as well as most of android, which is good and bad.

Is it possible to create a version that doesn’t break with each release?

Are you using a standard API to do this work, or are you hacking the byte code?

Chris

**Comment by gektor650** [comment]
> Is it possible to create a version that doesn’t break with each release?

As I mentioned above, I don't want to spend much time on support, so believe me, I want to create a version that doesn't break each release.

But some unpredicted situations appear, like once they changed an abstract class to interface in the API, etc.

I will look at how to support new versions of AS in the nearest feature.

**Comment by realityexpander** [comment]
OK thank you. That makes sense. Android is a fast moving target now.

Chris

**Comment by realityexpander** [comment]
I will have to use a release version of AS to make this work.
