### ISSUE TITLE
Not working on Android Studio Electric Eel

### ISSUE THREAD

**Issue by mayankwadhwa** [itkacher/OkHttpProfiler#34]
Please help plugin is not working on the new Android Studio Electric Eel.

**Comment by liangjingkanji** [comment]
Approve

**Comment by oxied** [comment]
Approve, not working on Android Studio Electric Eel !

**Comment by douglascarvalho** [comment]
same here!

**Comment by hunterkage** [comment]
Same for me, I tried to uninstall and install it again but still not working 😞

**Comment by gektor650** [comment]
Yeap, it seems like they have changed the realization of the new Android Studio. I am searching for the solutions

**Comment by t3xtwrit3r** [comment]
same here

**Comment by jehadmashhour** [comment]
Same here

**Comment by oxied** [comment]
@gektor650 any updates on this?

**Comment by gektor650** [comment]
> @gektor650 any updates on this?

Russian warship go fuck yourself!

**Comment by gektor650** [comment]
Sorry, guys, I am working on the issue, but they changed a lot, and I should figure it out from scratch.
Also, I don't have much time, because our neighbor is destroying Ukrainian cities and I have some work with it too.

So any help will be appreciated.
 
p.s. I will try to shut down this plugin for russia territory, so if you are from that area - feel free to uninstall the plugin.

**Comment by oxied** [comment]
> Russian warship go fuck yourself!

I'm not from Russia, lol. And keep your mouth shut, please. War is bad.

**Comment by gektor650** [comment]
<img width="993" alt="Screenshot 2023-01-19 at 08 56 45" src="https://user-images.githubusercontent.com/1488886/213553285-c24fcecb-5a27-4da7-b998-ed7c7c76a4a2.png">
Please, delete the plugin and proceed to the exit. 
It's great that you can change your country, but still, you know the course of the ship.

**Comment by oxied** [comment]
You are so funny, man.

**Comment by oxied** [comment]
I'm not russian, not living in Russia. Before making some conclusion, you can ask me, where I'm from and where I'm living. Also you can ask about my position about war and what I did to stop it. 

мирного неба всій Україні.

**Comment by gektor650** [comment]
> I'm not russian, not living in Russia. Before making some conclusion, you can ask me, where I'm from and where I'm living. Also you can ask about my position about war and what I did to stop it.
> 
> мирного неба всій Україні.

Said Gleb Mozheiko from Rostov. 

Слава Україні!

**Comment by oxied** [comment]
Yes, I was living in Rostov for some time. Did you have a foreign passport to travel abroad? )

**Comment by liangjingkanji** [comment]
> Yes, I was living in Rostov for some time. Did you have an international passport to travel abroad? )

Damn aggressors ! 
Waiting for your home to be blown up by a missile ! Waiting for Putin to call you to the battlefield to die !

**Comment by gektor650** [comment]
S

> <img alt="изображение" width="323" src="https://user-images.githubusercontent.com/1070647/213559156-88e6ccdc-dd16-4ae9-9bfe-3133a2d84ef8.png">
> 
> :)
> If I like quick conclusions as you, I would say, it's very easy to go fuck yourself in Canada. But I don't, bro.

You can still go and fuck yourself. I never wanted you as a user. Just live your life. But somewhere outside. I don't care. 
Thanks for pointing me to the right thing - all russian speakers should be banned. 
All your messages will be deleted. 
Have a nice nothing.

**Comment by oxied** [comment]
Do not forget to delete your messages as well

**Comment by Vrachno** [comment]
Really grateful for your contribution in these troubled times.  сла́ва Украї́ні!

**Comment by gektor650** [comment]
Thanks all for your patience.
Here is a new version of the plugin. 
It will be available after review, but you can download it and setup manually right now.
https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/279720
