### ISSUE TITLE
No data received after updating to Android Studio Electric Eel | 2022.1.1

### ISSUE THREAD

**Issue by elhm** [itkacher/OkHttpProfiler#35]
Won't work after updating Android Studio to latest stable Eel:

`Android Studio Electric Eel | 2022.1.1
Build #AI-221.6008.13.2211.9477386, built on January 11, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1`

![Screenshot 2023-01-20 at 12 56 50](https://user-images.githubusercontent.com/6544556/213689682-ea91e870-3518-442b-83f1-779a023466e4.png)

**Comment by hunterkage** [comment]
Same for me

**Comment by gektor650** [comment]
Fix submitted. Please, look here:
https://github.com/itkacher/OkHttpProfiler/issues/34#issuecomment-1397858928

**Comment by gektor650** [comment]
Update is ready on the market
