### ISSUE TITLE
Curl request feature

### ISSUE THREAD

**Issue by mistamek** [itkacher/OkHttpProfiler#4]
Thanks for such a terrific plugin. But is it possible to add the feature of presenting the request in curl format, as does Postman, for example?

And is it worth waiting for the source code of the plugin itself? I could provide a pull-request for such a feature, or implement it in a local assembly.

**Comment by itkacher** [comment]
Hi! Thanks for the request. I didn't think about curl as a feature, but I will add, this is a nice suggestion. 

I will add the plugin code here, but not now. I need to complete some things before going publish :)

**Comment by itkacher** [comment]
Hi! I have added the feature in a version 1.0.7 (plugin) + 1.0.4 (an interceptor library). The plugin will appear during two days (JetBrains review).
