### ISSUE TITLE
Plugin not working for Android Studio Jellyfish | 2023.3.1

### ISSUE THREAD

**Issue by Nckatharotiya** [itkacher/OkHttpProfiler#44]
Android Studio Jellyfish | 2023.3.1
Build #AI-233.14808.21.2331.11709847, built on April 12, 2024

**Comment by devonEdison** [comment]
me too Android Studio Jellyfish | 2023.3.1 not working

**Comment by gektor650** [comment]
Fixed in version 1.0.32
It will be available after approval from JetBrains. 
Meanwhile, you can download a new version by the link:

https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/edit/versions/stable/532589
