### ISSUE TITLE
Plugin not working for Android Studio  Koala | 2024.1.1

### ISSUE THREAD

**Issue by Nckatharotiya** [itkacher/OkHttpProfiler#45]
Android Studio Koala | 2024.1.1
Build #AI-241.15989.150.2411.11948838, built on June 10, 2024

**Comment by gektor650** [comment]
I uploaded a new version to the Plugin Marketplace. It will be available in a few days after approve.
However, you can install it manually from here:
https://github.com/gektor650/OkHttpProfiler-AndroidStudio-Plugin/blob/master/OkHttpProfiler-1.0.33.zip
