### ISSUE TITLE
Failed to resolve: com.itkacher.okhttpprofiler:okhttpprofiler:1.0.7

### ISSUE THREAD

**Issue by imanshul** [itkacher/OkHttpProfiler#50]
I'm not able to resolve the library with jCenter() or mavenCentral() with gradle **7.4.2**

**Comment by gektor650** [comment]
Please use the latest:
```
implementation("io.nerdythings:okhttp-profiler:1.1.1")
```

jFrog is down. I will not be able to resurrect it. 

If you can't use the latest, use:
https://central.sonatype.com/artifact/com.localebro/okhttpprofiler/versions
```
implementation("com.localebro:okhttpprofiler:1.0.8")
```

Let me know if it works for you or not.
