### ISSUE TITLE
Plugin not working for Android Studio Ladybug | 2024.2.1

### ISSUE THREAD

**Issue by Nckatharotiya** [itkacher/OkHttpProfiler#51]
Android Studio Ladybug | 2024.2.1
Build #AI-242.21829.142.2421.12409432, built on September 24, 202

**Comment by gektor650** [comment]
The fix has been sent for review. It will be available in a few days.
Meanwhile, you can download it and install it manually from here:
https://github.com/itkacher/OkHttpProfiler/tree/master/releases/okhttp-profiler-plugin
Feel free to let me know if you have any questions.

And don't forget to set a fair review about it here:
https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/

Also, you can support me by subscribing to my channel:
https://www.youtube.com/channel/UCp1a3wOSkEVrh4qL3Ss4_jw

Have a nice day!
